# Generated by Django 5.1.2 on 2024-11-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="discord_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
