# Generated by Django 5.1.2 on 2024-11-07 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("paths", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarshipapplication",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scholarship_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pathrecommendation",
            name="recommended_technology",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="path_recommendations",
                to="paths.technology",
            ),
        ),
        migrations.AddField(
            model_name="learningpath",
            name="technologies",
            field=models.ManyToManyField(
                related_name="learning_paths", to="paths.technology"
            ),
        ),
        migrations.AddField(
            model_name="userpathprogress",
            name="path",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_progress",
                to="paths.learningpath",
            ),
        ),
        migrations.AddField(
            model_name="userpathprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="path_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
